### ISSUE TITLE
Repository should be merged into TKMM-Team/Tkmm-Wiki or removed

### ISSUE THREAD

**Issue by WalkQuackBack** [TotkMods/tkmm#1]
There are two repositories with identical content and now that there is an organization for TKMM this repository should either be removed or merged into TKMM-Team/Tkmm-Wiki

**Comment by LordBubblesDev** [comment]
This is intentional in order to have a better URL with [totkmods.github.io/tkmm/](https://totkmods.github.io/tkmm/)

The other one in the organization we use for testing and basically making sure everything looks good before deploying changes to this one.
